source/website/Models/DressType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Website.Models
{
    public enum DressType
    {
        Bride,
        BridesMaid,
    }

}

source/website/Controllers/DressController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Website.Models;
using Dapper;
using Website.DatabaseModels;
using DressType = Website.Models.DressType;
using AutomaticModelStateValidation;
using System.Security.Cryptography;

namespace Website.Controllers
{
    [Route("/dress")]
    public class DressController : Controller
    {
        readonly IDbConnection connection;
        readonly IDbTransaction dbTransaction;

        public DressController(IDbConnection dbConnection, IDbTransaction dbTransaction)
        {
            this.connection = dbConnection;
            this.dbTransaction = dbTransaction;
        }

        [HttpGet("")]
        public IActionResult Home(DressesFilterModel model)
        {
            string sql =
                @"SELECT d.DressId, d.DressName, d.DressWebpage, d.Price, d.ProductDescription, d.DressType, d.DressApproval, d.Rating, d.ShopId, d.CreatedBy, d.Deleted, i.ImageId
                    FROM Dresses d
                    FULL OUTER JOIN DressImages di on d.DressId = di.DressId
                    FULL OUTER JOIN Images i on di.ImageId = i.ImageId
                    WHERE d.DressType = @DressType 
                    AND (d.Deleted <> 1 OR d.DressId = @DeletedDressId)
                    AND (i.ImageId is null
                        OR i.ImageId = (
                            Select top 1 di2.ImageId
                            From DressImages di2
                            Where di2.DressId = di.DressId
                            Order By di2.[Favourite], di2.[SequentialId]))
                    Order By d.[SequentialId]";

            var dresses =
                connection
                .Query<DressItemsQueryModel>(
                    sql,
                    new {
                        model.DressType,
                        model.DeletedDressId
                    }, dbTransaction)
                .Select(dress => {        
                    return new DressItem() {
                        DressId = dress.DressId,
                        Name = dress.DressName,
                        Price = dress.Price.ToString("C"),
                        Shop = "Need to do",
                        Description = dress.ProductDescription,
                        ImageId = dress.ImageId,
                        CreatedBy = Guid.Empty,
                        Approval = dress.DressApproval.ToString(),
                        Rating = "2",
                        Deleted = dress.Deleted
                    };
                })
                .ToList();

            var viewModel = new DressIndexModel() {
                DressType = DressType.Bride,
                Dresses = dresses
            };
            return View(viewModel);
        }

        [HttpGet("new")]
        [HttpPost("new")]
        public IActionResult NewDress(AddDressUrlModel model)
        {
            // TODO: Scrapes website
            var responseModel =
                new GetNewDressModel() {
                    Name = "",
                    Price = "",
                    Shop = "",
                    Description = "",
                    Images = null,
                    DressType = null,
                    Url = model.WebpageUrl
                };
            return View("GetNewDress", responseModel);
        }

        private DatabaseModels.DressType MapDressType(DressType modelDressType)
        {
            switch (modelDressType) {
                case DressType.Bride:
                    return DatabaseModels.DressType.Bride;
                case DressType.BridesMaid:
                    return DatabaseModels.DressType.BridesMaid;
            }
            return DatabaseModels.DressType.Bride;
        }


        [HttpPost("save")]
        [AutoValidateModel(nameof(NewDress))]
        public async Task<IActionResult> SaveDress(SaveDressModel model)
        {
            var dressId = Guid.NewGuid();
            foreach (var image in model.Images) {

                var imageId = Guid.NewGuid();
                var imageFileName = image.FileName;
                var imageName = System.IO.Path.GetFileName(image.FileName);
                var imageExtension = System.IO.Path.GetExtension(image.FileName);
                var imageContent = image.OpenReadStream().ReadFullyToArray();
                var imageHash = GetByteArrayHash(imageContent);

                var result = await connection.QueryFirstOrDefaultAsync<Guid?>("Select ImageId From Images Where Hash = @Hash", new { Hash = imageHash }, dbTransaction);

                if (result == null) {
                    await connection.ExecuteAsync(
                        @"Insert Images (ImageId, FileName, FileExtension, FileData, Hash) 
                    values (@ImageId, @FileName, @FileExtension, @FileData, @Hash)",
                        new Images() {
                            ImageID = imageId,
                            FileName = imageName,
                            FileExtension = imageExtension,
                            FileData = imageContent,
                            Hash = imageHash,
                        },
                        dbTransaction
                    );
                } else {
                    imageId = result.Value;
                }

                await connection.ExecuteAsync(
                    @"Insert DressImages (DressId, ImageId, Favourite) 
                    values (@DressId, @ImageId, @Favourite)",
                    new DressImages {
                        DressId = dressId,
                        ImageID = imageId,
                        Favourite = false
                    },
                    dbTransaction
                );
            }

            await connection.ExecuteAsync(
                @"Insert Dresses(DressId, DressName, DressWebpage, Price, ProductDescription, DressType, DressApproval, Rating, ShopId, WeddingId, CreatedBy, CreatedAt, ModifiedBy, ModifiedAt, Deleted, DeletedAt) 
                       values (@DressId, @DressName, @DressWebpage, @Price, @ProductDescription, @DressType, @DressApproval, @Rating, @ShopId, @WeddingId, @CreatedBy, @CreatedAt, @ModifiedBy, @ModifiedAt, @Deleted, @DeletedAt)",
                    new DressSaveModel() {
                        DressId = dressId,
                        DressName = model.Name,
                        DressWebpage = model.Url,
                        Price = model.Price.Value,
                        ProductDescription = model.Description,
                        DressType = MapDressType(model.DressType.Value),
                        DressApproval = DressApproval.NeedsApproval,
                        Rating = null,
                        ShopId = Guid.Empty, 
                        WeddingId = Guid.Empty,
                        CreatedBy = Guid.Empty, //curent user
                        CreatedAt = DateTimeOffset.Now,
                        ModifiedBy = Guid.Empty,
                        ModifiedAt = DateTimeOffset.Now,
                        Deleted = false,
                        DeletedAt = null
                    },
                    dbTransaction
                );

            return RedirectToAction(nameof(GetDressDetails), new { dressId });
        }

        private string GetByteArrayHash(byte[] byteArray)
        {
            using (SHA1CryptoServiceProvider sha1 = new SHA1CryptoServiceProvider()) {
                return Convert.ToBase64String(sha1.ComputeHash(byteArray));
            }
        }

        [HttpGet("{dressId}")]
        public async Task<IActionResult> GetDressDetails(Guid dressId)
        {
            var sqlDressImages =
                    @"SELECT i.ImageId, di.Favourite
                    FROM DressImages di
                    JOIN Images i on di.ImageId = i.ImageId
                    WHERE di.DressId = @DressId
                    ORDER BY di.SequentialId";

            var dressImages = 
                connection
                .Query<DressImageModel>(
                sqlDressImages, new { DressId = dressId }, dbTransaction)
                .ToList();

            var dress =
                connection
                .QueryFirst<DressQueryModel>(
                    "Select DressId, DressName, DressWebpage, Price, ProductDescription, DressType, DressApproval, Rating, ShopId, CreatedBy FROM Dresses WHERE DressId = @DressId",
                    new { DressId = dressId }, dbTransaction);

            var image = dressImages.FirstOrDefault(x => x.Favourite);
            if (image == null && dressImages.Count > 0) {
                image = dressImages[0];
            }
            var primaryImageId = image == null ? null : new Guid?(image.ImageId);

            var model = new DressDetailsModel() {
                Name = dress.DressName,
                DressWebpage = dress.DressWebpage,
                Price = dress.Price.ToString("C"),
                Shop = dress.ShopId,
                Description = dress.ProductDescription,
                PrimaryImageId = primaryImageId,
                Images = dressImages.Select(x => x.ImageId).ToList(),
                Comments = new List<string>() {
                    "Love Love Love!",
                    "So pretty!",
                },
                Approval = dress.DressApproval.ToString(),
                Rating = dress.Rating,
                CreatedBy = dress.CreatedBy, //current user
                DressType = DressType.Bride,
            };
            return View(model);
        }

        [HttpGet("{dressId}/edit")]
        public async Task<IActionResult> EditDressDetails(Guid dressId)
        {
            var dress =

source/website/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Website.Models;

namespace Website.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return Redirect("dress");
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

source/website/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Website.Models;

namespace website.Controllers
{
    [Route ("/image")] 
    public class ImageController : Controller 
    {
        readonly IDbConnection connection;
        readonly IDbTransaction dbTransaction;
        private object dbtranscation;

        public ImageController(IDbConnection dbConnection, IDbTransaction dbTransaction)
        {
            this.connection = dbConnection;
            this.dbTransaction = dbTransaction;
        }

        [HttpGet("{imageId}")]
        public async Task<IActionResult> GetImage(Guid imageId)
        {
            var sql = "SELECT FileName, FileExtension, FileData FROM Images Where ImageId = @ImageId";

            var image = await connection.QueryFirstOrDefaultAsync<ImageModel>(sql, new { ImageId = imageId }, dbTransaction);

            if (image == null) {
                return NotFound();
            }

            return File(image.FileData, $"image/{image.FileExtension}");
        }
    }
}

source/website/Views/Dress/EditDressDetails.cshtml
@model EditDressDetailsModel
@{
    ViewData["Title"] = "EditDressDetails";
}

<h2>EditDressDetails</h2>

<div>
    <img src="#" alt="Alternate Text" />

</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateDressDetails" asp-route-id="@Model.DressId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="new-dress-WebpageUrl">
                <label asp-for="DressWebpage" class="control-label"></label>
                <input asp-for="DressWebpage" class="form-control" />
                <span asp-validation-for="DressWebpage" class="text-danger"></span>
            </div>
            <div class="new-dress-name">
                <label asp-for="DressName" class="control-label"></label>
                <input asp-for="DressName" class="form-control" />
                <span asp-validation-for="DressName" class="text-danger"></span>
            </div>
            <div class="new-dress-price">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="new-dress-description">
                <label asp-for="ProductDescription" class="control-label"></label>
                <input asp-for="ProductDescription" class="form-control" />
                <span asp-validation-for="ProductDescription" class="text-danger"></span>
            </div>
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary active">
                    <input type="radio" asp-for="DressType" checked value="Bride"> Bride
                </label>
                <label class="btn btn-secondary">
                    <input type="radio" asp-for="DressType" autocomplete="off" value="Bridesmaid"> Bridesmaid
                </label>
                <span asp-validation-for="DressType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

source/website/Views/Dress/GetDressDetails.cshtml
@model DressDetailsModel

@{
    ViewData["Title"] = "GetDress";
}

<div class="navigation">
    <div class=" nav nav-prev"><</div>
    <div class="nav nav-next">></div>
    <div class="nav nav-x">x</div>
</div>

<div class="dress-details-image">
    <img src="@Url.Action("GetImage", "Image", new { imageId = Model.PrimaryImageId ?? Guid.Empty })" />
</div>

<h2>@Model.Name</h2>
<div class="dress-shop">@Model.Shop</div>
@if (Model.Price != null)
{
    <div class="dress-price">
        | @Model.Price
    </div>
}
<div class="dress-desc-type">| @Model.DressType</div>

<div class="dress-details-description">@Model.Description</div>

<div class="dress-recommendation">This dress was recommended by @Model.CreatedBy</div>

<div class="dress-comments">
    <div class="previous-comments">
        @foreach (var comment in Model.Comments)
        {
            <div class="comment">@comment</div>
        }
    </div>

    <form asp-action="NewComment">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="add-new-comment">
            <label asp-for="NewComment" class="control-label">Add Comment</label>
            <input asp-for="NewComment" class="form-control" />
            <span asp-validation-for="NewComment" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </form>

    <div class="dress-details-buttons">
        <a asp-action="EditDressDetails" asp-route-id="@Model.DressId">
            <div class="edit">Edit</div>
        </a>
        <form asp-action="DeleteDressDetails" asp-route-id="@Model.DressId">
            <button class="delete">Delete</button>
        </form>
    </div>


</div>






source/website/Views/Dress/GetNewDress.cshtml
@model Website.Models.GetNewDressModel

@{
    ViewData["Title"] = "GetNewDress";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="SaveDress" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="new-dress-WebpageUrl">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="new-dress-image">
                <label asp-for="Images" class="control-label"></label>
                <input type="file" asp-for="Images" class="form-control" multiple />
                <span asp-validation-for="Images" class="text-danger"></span>
            </div>


            <div class="new-dress-name">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="new-dress-price">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="new-dress-description">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary active">
                    <input type="radio" asp-for="DressType" checked value="Bride"> Bride
                </label>
                <label class="btn btn-secondary">
                    <input type="radio" asp-for="DressType" autocomplete="off" value="Bridesmaid"> Bridesmaid
                </label>
                <span asp-validation-for="DressType" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


source/website/Views/Dress/Home.cshtml
@model DressIndexModel

@{
    ViewData["Title"] = "Home Page";
}

<div>
    Add a Dress
    <form asp-controller="dress" asp-action="new" method="post">
       Dress Webpage: <input name="WebpageUrl" type="url" />
       <button type="Submit">Search</button>
    </form>
</div>

<div class="dress-types">
    <a class="dress-type dress-type-bride @(Model.DressType == DressType.Bride ? "active" : "")"
       asp-controller="Dress" 
       asp-action="Home" 
       asp-route-dresstype="@DressType.Bride">Bride</a><!--
 --><a class="dress-type dress-type-bridemaids @(Model.DressType == DressType.BridesMaid ? "active" : "")"
       asp-controller="Dress" 
       asp-action="Home" 
       asp-route-dresstype="@DressType.BridesMaid">Bridesmaids</a>
</div>

<div class="dress-filters">
    <!--name, price, shop, favourite, rank, approved, search -->
</div>

<div>
    @foreach (var dress in Model.Dresses) {
        if (!dress.Deleted) {
    <a asp-action="GetDressDetails" asp-route-dressId="@dress.DressId">
        <div class="dress-item">
            <div class="dress-image">
                <img src="@Url.Action("GetImage", "Image", new { imageId = dress.ImageId})" />
            </div>
            <div class="dress-item-header">

                <div class="dress-name">
                    @dress.Name
                </div>

                <div class="dress-shop">
                    @dress.Shop
                </div>

                @if (dress.Price != null) {
                    <div class="dress-price">
                        | @dress.Price
                    </div>
                }
            </div>
            <div class="dress-description">
                @dress.Description
            </div>

            <div class="bride-options">
                <div class="dress-rating">
                    @dress.Rating
                </div>

                <div class="dress-approval">
                    @dress.Approval
                </div>
            </div>
        </div>
    </a>
    } else {
    <div class="dress-deleted">
        The dress has been deleted.
        <form asp-action="UndoDelete" asp-route-dressId="@dress.DressId">
            <button class="undo-delete">Undo</button>
        </form>
    </div>
        }
    }
</div>